name: Node Integration
on: push
jobs: 
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:21.7.1
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v2
      - run: npm install